"""
test/enjl/reference
===================
Beta-equilibrium reference tables produced by the author's own Maple
implementation of the extended NJL model (Xia 2024, PRD 110, 014022).

These are ground truth for `eos/enjl/`: they were generated by the code that
produced the figures of the paper, so they pin the model far more tightly than
the two or three significant figures the paper prints.

Files, one per parameter set (f_q = f_u = f_d = f_s; B in GeV/fm^3):

    Beta_fq1.0_B0.dat    f_q = 1.0   B = 0        280 rows
    Beta_fq1.0_B1.dat    f_q = 1.0   B = 1        279 rows
    Beta_fq0.7_B0.dat    f_q = 0.7   B = 0        253 rows
    Beta_fq0.7_B1.dat    f_q = 0.7   B = 1        273 rows
    Beta_fq0.5_B1.dat    f_q = 0.5   B = 1        383 rows, extra columns

All are tab-separated with one header row of column names, n_b from 0.01 to
10 fm^-3. `load_reference` below returns them as a plain dict of numpy arrays
with the blank columns dropped.

Four traps in the column semantics:

  * `nsq` and `Sigmaq` (q = u, d, s) are NOT the same quantity. `nsq` is the
    quark scalar density *without* the vacuum Dirac-sea term; `Sigmaq` is the
    effective scalar density nbar^s_q of paper Eq. (6), vacuum term included.
    It is `Sigmaq` that enters the gap equation.
  * On rows where a quark mass has been driven to its current mass the Maple
    run clamps `Sigmaq` to exactly 0 rather than reporting the small residual
    value. Skip those rows when checking the gap equation.
  * `munr`, not `mun`, is the baryon chemical potential. They agree while
    baryons are present and diverge by hundreds of MeV once the baryons have
    dissolved, where `munr` = mu_u + 2 mu_d and `mun` is the vanishing
    neutron's own potential.
  * `Beta_fq0.5_B1.dat` is 180 solved rows plus 203 rows of linear
    interpolation across two Maxwell plateaus. `solved_rows()` below selects
    the solved ones; quantitative checks on the interpolated rows are
    meaningless.
  * `mue` and `mumu` are written as the lepton MASS on rows where that lepton
    is absent, not as the chemical potential. mu_e is still nonzero there and
    is recoverable as mu_d - mu_u.
"""
import os

import numpy as np

REFERENCE_DIR = os.path.dirname(os.path.abspath(__file__))

#: file name -> (f_q, B in GeV/fm^3)
PARAMETER_SETS = {
    "Beta_fq1.0_B0.dat": (1.0, 0.0),
    "Beta_fq1.0_B1.dat": (1.0, 1.0),
    "Beta_fq0.7_B0.dat": (0.7, 0.0),
    "Beta_fq0.7_B1.dat": (0.7, 1.0),
    "Beta_fq0.5_B1.dat": (0.5, 1.0),
}

#: species present in every table
SPECIES = ("p", "n", "L", "u", "d", "s", "e", "mu")


def load_reference(filename):
    """Load one reference table as {column name -> float array}.

    Blank/unnamed columns (Maple writes stray tabs) and Maple's derivative
    columns are dropped. Rows whose n_b is not a finite number are dropped;
    non-numeric cells elsewhere ('--' appears in the f_q = 0.5 file) become
    NaN so a caller can mask them.
    """
    path = os.path.join(REFERENCE_DIR, filename)
    with open(path) as handle:
        names = [c.strip() for c in handle.readline().rstrip("\n").split("\t")]
    raw = np.genfromtxt(path, delimiter="\t", skip_header=1,
                        missing_values="--", filling_values=np.nan)
    if raw.ndim == 1:
        raw = raw[None, :]
    cols = {}
    for i, name in enumerate(names):
        if not name or name.startswith("Derivative"):
            continue
        cols[name] = raw[:, i].astype(float)
    good = np.isfinite(cols["nB"])
    return {k: v[good] for k, v in cols.items()}


def solved_rows(col):
    """Boolean mask of rows that are genuine solver output.

    Only `Beta_fq0.5_B1.dat` contains anything else: 203 of its 383 rows are
    linear interpolation across the two Maxwell plateaus, and a blank `munr`
    is the marker for them. Every quantitative check must be restricted to
    this mask, because on the interpolated rows `epa` disagrees with `E/n_b`
    and the gap equation does not hold.
    """
    return np.isfinite(col["munr"])


#: Rows that are non-converged solver output and cannot be repaired, keyed by
#: file; values are n_b [fm^-3], matched to 1e-6.
BAD_ROWS = {
    #   3.4: this row's own columns are self-consistent (`nB` matches the sum
    #        of its species densities, and epa * nB == E to 8e-8), but it
    #        fails Eq. (23) by 9.6 MeV in the proton channel and by 3-6 MeV in
    #        u, d and s. The two rows below it satisfy the same identity to
    #        1e-8, and the two above it are stale-`nB` rows, so it reads as
    #        the first row of a non-converged run rather than a lone glitch.
    "Beta_fq0.7_B0.dat": (3.4,),
}


def stale_density_rows(col):
    """Mask of rows whose `nB` disagrees with the sum of their own densities.

    Eight rows of `Beta_fq0.7_B0.dat` are like this, with `nB` high by one
    grid step. Their `epa` equals E / (sum of the densities) rather than
    E / `nB`, to 1e-10, which identifies the sum as the true density and the
    `nB` column as stale — most likely a density label written from the
    following iteration. Their other columns come from a mixture of
    iterations too, so substituting the corrected density does not rescue
    them (the mean-field residual stays around 2 MeV): they can only be
    excluded, not repaired.
    """
    n_sum = (col["np"] + col["nn"] + col["nL"]
             + (col["nu"] + col["nd"] + col["ns"]) / 3.0)
    return np.abs(n_sum - col["nB"]) > 1.0e-5


def bad_rows(col, filename):
    """Mask of rows to exclude: stale-`nB` rows plus the `BAD_ROWS` entries.

    With these out, every file satisfies its own identities uniformly across
    the full 0.01-10 fm^-3 range; with them in, `Beta_fq0.7_B0.dat` looks two
    orders of magnitude worse than it is.
    """
    mask = stale_density_rows(col)
    for n_b in BAD_ROWS.get(filename, ()):
        mask = mask | (np.abs(col["nB"] - n_b) < 1.0e-6)
    return mask


def baryon_potential(col):
    """The baryon chemical potential mu_b [MeV] — the `munr` column.

    Not `mun`: past the deconfinement transition the printed `mun` is the
    dissolved neutron's own potential and is hundreds of MeV away from mu_b.
    """
    return col["munr"]


def electron_potential(col):
    """The electron chemical potential mu_e [MeV].

    The `mue` column carries the electron MASS (0.511) on rows with no
    electrons, so it cannot be read directly there. On those rows mu_e follows
    from Eq. (23) applied to the two lightest quarks, mu_e = mu_d - mu_u.
    """
    return np.where(col["ne"] > 0.0, col["mue"], col["mud"] - col["muu"])


#: a species counts as present above this fraction of n_b; below it the printed
#: mu_i is a stale threshold value and Eq. (23) does not apply to it.
PRESENT_FRACTION = 1.0e-4


def present(col, species):
    """Mask of rows where `species` is present enough for Eq. (23) to hold."""
    return col["n" + species] > PRESENT_FRACTION * col["nB"]
