"""
test/enjl/reference
===================
Beta-equilibrium reference tables produced by the author's own Maple
implementation of the extended NJL model (Xia 2024, PRD 110, 014022).

These are ground truth for `eos/enjl/`: they were generated by the code that
produced the figures of the paper, so they pin the model far more tightly than
the two or three significant figures the paper prints.

Files, one per parameter set (f_q = f_u = f_d = f_s; B in GeV/fm^3):

    Beta_fq1.0_B0.dat    f_q = 1.0   B = 0        280 rows
    Beta_fq1.0_B1.dat    f_q = 1.0   B = 1        279 rows
    Beta_fq0.7_B0.dat    f_q = 0.7   B = 0        253 rows
    Beta_fq0.7_B1.dat    f_q = 0.7   B = 1        273 rows
    Beta_fq0.5_B1.dat    f_q = 0.5   B = 1        383 rows, extra columns

All are tab-separated with one header row of column names, n_b from 0.01 to
10 fm^-3. Column meanings, units and the exact identities they satisfy are
documented in `docs/enjl/REFERENCE_TABLES.md`; `load_reference` below returns
them as a plain dict of numpy arrays with the blank columns dropped.

Four traps, all documented at length in that file:

  * `nsq` and `Sigmaq` (q = u, d, s) are NOT the same quantity. `nsq` is the
    quark scalar density *without* the vacuum Dirac-sea term; `Sigmaq` is the
    effective scalar density nbar^s_q of paper Eq. (6), vacuum term included.
    It is `Sigmaq` that enters the gap equation.
  * On rows where a quark mass has been driven to its current mass the Maple
    run clamps `Sigmaq` to exactly 0 rather than reporting the small residual
    value. Skip those rows when checking the gap equation.
  * `munr`, not `mun`, is the baryon chemical potential. They agree while
    baryons are present and diverge by hundreds of MeV once the baryons have
    dissolved, where `munr` = mu_u + 2 mu_d and `mun` is the vanishing
    neutron's own potential.
  * `Beta_fq0.5_B1.dat` is 180 solved rows plus 203 rows of linear
    interpolation across two Maxwell plateaus. `solved_rows()` below selects
    the solved ones; quantitative checks on the interpolated rows are
    meaningless.
  * `mue` and `mumu` are written as the lepton MASS on rows where that lepton
    is absent, not as the chemical potential. mu_e is still nonzero there and
    is recoverable as mu_d - mu_u.
"""
import os

import numpy as np

REFERENCE_DIR = os.path.dirname(os.path.abspath(__file__))

#: file name -> (f_q, B in GeV/fm^3)
PARAMETER_SETS = {
    "Beta_fq1.0_B0.dat": (1.0, 0.0),
    "Beta_fq1.0_B1.dat": (1.0, 1.0),
    "Beta_fq0.7_B0.dat": (0.7, 0.0),
    "Beta_fq0.7_B1.dat": (0.7, 1.0),
    "Beta_fq0.5_B1.dat": (0.5, 1.0),
}

#: species present in every table
SPECIES = ("p", "n", "L", "u", "d", "s", "e", "mu")


def load_reference(filename):
    """Load one reference table as {column name -> float array}.

    Blank/unnamed columns (Maple writes stray tabs) and Maple's derivative
    columns are dropped. Rows whose n_b is not a finite number are dropped;
    non-numeric cells elsewhere ('--' appears in the f_q = 0.5 file) become
    NaN so a caller can mask them.
    """
    path = os.path.join(REFERENCE_DIR, filename)
    with open(path) as handle:
        names = [c.strip() for c in handle.readline().rstrip("\n").split("\t")]
    raw = np.genfromtxt(path, delimiter="\t", skip_header=1,
                        missing_values="--", filling_values=np.nan)
    if raw.ndim == 1:
        raw = raw[None, :]
    cols = {}
    for i, name in enumerate(names):
        if not name or name.startswith("Derivative"):
            continue
        cols[name] = raw[:, i].astype(float)
    good = np.isfinite(cols["nB"])
    return {k: v[good] for k, v in cols.items()}


def solved_rows(col):
    """Boolean mask of rows that are genuine solver output.

    Only `Beta_fq0.5_B1.dat` contains anything else: 203 of its 383 rows are
    linear interpolation across the two Maxwell plateaus, and a blank `munr`
    is the marker for them. Every quantitative check must be restricted to
    this mask, because on the interpolated rows `epa` disagrees with `E/n_b`
    and the gap equation does not hold.
    """
    return np.isfinite(col["munr"])


def baryon_potential(col):
    """The baryon chemical potential mu_b [MeV] — the `munr` column.

    Not `mun`: past the deconfinement transition the printed `mun` is the
    dissolved neutron's own potential and is hundreds of MeV away from mu_b.
    """
    return col["munr"]


def electron_potential(col):
    """The electron chemical potential mu_e [MeV].

    The `mue` column carries the electron MASS (0.511) on rows with no
    electrons, so it cannot be read directly there. On those rows mu_e follows
    from Eq. (23) applied to the two lightest quarks, mu_e = mu_d - mu_u.
    """
    return np.where(col["ne"] > 0.0, col["mue"], col["mud"] - col["muu"])


#: a species counts as present above this fraction of n_b; below it the printed
#: mu_i is a stale threshold value and Eq. (23) does not apply to it.
PRESENT_FRACTION = 1.0e-4


def present(col, species):
    """Mask of rows where `species` is present enough for Eq. (23) to hold."""
    return col["n" + species] > PRESENT_FRACTION * col["nB"]
