"""
M1 gate (load-bearing): nucleonic SNM at T=0.

Golden reference points and recomputed NMPs from report §2.7 (generated by
dd2_reference_validation.py). Tolerances from report §3.x:
golden thermodynamics < 1e-4 relative, NMPs < 0.5 MeV absolute.
A factor-4 E_sym failure here means the tau_3 = ±1 convention is mis-set.
"""
import pytest

from eos.dd2 import Parametrization, compute_nmp, solve_snm_t0

REL = 1e-4

# report §2.7 (b): n_B -> (sigma, omega0, m*/m, Sigma_R, eps, P, mu_B)
GOLDEN_SNM = {
    0.149065: dict(sigma=38.4344, omega0=24.9255, mstar_m=0.56254,
                   Sigma_R=2.9808, eps=137.5715, P=None, mu_B=922.894),
    0.16: dict(sigma=40.5684, omega0=26.4874, mstar_m=0.54247,
               Sigma_R=1.9849, eps=147.6750, P=0.34289, mu_B=925.112),
}

# report §2.7 (a), recomputed column
GOLDEN_NMP = dict(n_sat=0.149065, E_sat=-16.023, m_eff_ratio=0.5625,
                  K_sat=242.68, Q_sat=168.6, E_sym=31.669, L_sym=55.03)


@pytest.fixture(scope="module")
def par():
    return Parametrization.from_dd2_defaults()


@pytest.mark.parametrize("n_B", sorted(GOLDEN_SNM))
def test_golden_snm_row(par, n_B):
    gold = GOLDEN_SNM[n_B]
    p = solve_snm_t0(par, n_B)
    assert p.sigma == pytest.approx(gold["sigma"], rel=REL)
    assert p.omega0 == pytest.approx(gold["omega0"], rel=REL)
    assert p.m_eff / par.m_nucleon == pytest.approx(gold["mstar_m"], rel=REL)
    assert p.Sigma_R == pytest.approx(gold["Sigma_R"], rel=REL)
    assert p.eps == pytest.approx(gold["eps"], rel=REL)
    if gold["P"] is None:
        assert abs(p.P) < 1e-3          # saturation: P ~ 0
    else:
        assert p.P == pytest.approx(gold["P"], rel=REL)
    # SNM with the average-mass convention: mu_n = mu_p = mu_B
    assert p.mu_n == pytest.approx(gold["mu_B"], rel=REL)
    assert p.mu_p == pytest.approx(gold["mu_B"], rel=REL)
    assert p.rho0 == 0.0


@pytest.mark.parametrize("n_B", [0.02, 0.08, 0.149065, 0.16, 0.24, 0.32, 0.48])
def test_hugenholtz_van_hove(par, n_B):
    # solve_snm_t0 raises internally above 1e-8; assert the actual residual
    # is at round-off level.
    p = solve_snm_t0(par, n_B)
    assert abs(p.hvh_rel) < 1e-12


def test_asymmetric_composition_hvh(par):
    from eos.dd2 import solve_composition_t0
    p = solve_composition_t0(par, n_n=0.15, n_p=0.01)
    assert abs(p.hvh_rel) < 1e-12
    assert p.rho0 < 0.0                 # neutron-rich: negative rho_0
    assert p.mu_n > p.mu_p


def test_nmp_reproduction(par):
    nmp = compute_nmp(par)
    assert nmp["n_sat"] == pytest.approx(GOLDEN_NMP["n_sat"], abs=5e-5)
    assert nmp["m_eff_ratio"] == pytest.approx(GOLDEN_NMP["m_eff_ratio"], abs=1e-3)
    for key in ("E_sat", "K_sat", "Q_sat", "E_sym", "L_sym"):
        assert nmp[key] == pytest.approx(GOLDEN_NMP[key], abs=0.5), key
    assert abs(nmp["P_sat"]) < 1e-8     # brentq lands on the P=0 root


if __name__ == "__main__":
    # Gate report: max errors vs golden rows and NMPs.
    par = Parametrization.from_dd2_defaults()
    print("golden SNM rows (relative errors):")
    for n_B, gold in GOLDEN_SNM.items():
        p = solve_snm_t0(par, n_B)
        got = dict(sigma=p.sigma, omega0=p.omega0,
                   mstar_m=p.m_eff / par.m_nucleon, Sigma_R=p.Sigma_R,
                   eps=p.eps, P=p.P, mu_B=p.mu_n)
        errs = {k: abs(got[k] / v - 1.0) for k, v in gold.items()
                if v is not None}
        worst = max(errs, key=errs.get)
        print(f"  n_B={n_B}: max rel err = {errs[worst]:.2e} ({worst})"
              f"   [HVH={p.hvh_rel:.1e}]")
    print("NMPs (value / golden / abs err):")
    nmp = compute_nmp(par)
    for k, v in GOLDEN_NMP.items():
        print(f"  {k:12s} {nmp[k]:10.4f} {v:10.4f} {abs(nmp[k] - v):.2e}")
