"""
M2 gate: beta-equilibrium npemu matter at T=0.

Golden row (c) from report §2.7 (generated by dd2_reference_validation.py),
tolerance 1e-4 relative; HVH < 1e-8 (asserted at round-off here).
"""
import pytest

from eos.dd2 import Parametrization, solve_beta_eq_t0
from eos.general.particles import Muon

REL = 1e-4

# report §2.7 (c), n_B = 0.16 fm^-3
GOLD_C = dict(Y_p=0.05809, mstar_m=0.55361, rho0=-6.5163, mu_e=123.059,
              eps=152.7743, P=3.05025, mu_n=973.904, mu_p=850.845)

NB_GRID = [0.05, 0.08, 0.12, 0.16, 0.24, 0.32, 0.48]


@pytest.fixture(scope="module")
def par():
    return Parametrization.from_dd2_defaults()


def test_golden_beta_row(par):
    p = solve_beta_eq_t0(par, 0.16)
    assert p.Y_p == pytest.approx(GOLD_C["Y_p"], rel=REL)
    assert p.m_eff / par.m_nucleon == pytest.approx(GOLD_C["mstar_m"], rel=REL)
    assert p.rho0 == pytest.approx(GOLD_C["rho0"], rel=REL)
    assert p.mu_e == pytest.approx(GOLD_C["mu_e"], rel=REL)
    assert p.eps == pytest.approx(GOLD_C["eps"], rel=REL)
    assert p.P == pytest.approx(GOLD_C["P"], rel=REL)
    assert p.mu_n == pytest.approx(GOLD_C["mu_n"], rel=REL)
    assert p.mu_p == pytest.approx(GOLD_C["mu_p"], rel=REL)


@pytest.mark.parametrize("n_B", NB_GRID)
def test_hvh_and_closures(par, n_B):
    p = solve_beta_eq_t0(par, n_B)
    assert abs(p.hvh_rel) < 1e-12
    # beta condition, charge neutrality, baryon number
    assert p.mu_n - p.mu_p == pytest.approx(p.mu_e, abs=1e-6)
    assert p.n_p == pytest.approx(p.n_e + p.n_mu, rel=1e-9)
    assert p.n_n + p.n_p == pytest.approx(n_B, rel=1e-12)
    # muons appear exactly above their threshold
    assert (p.n_mu > 0.0) == (p.mu_e > Muon.mass)


def test_warm_start_sweep(par):
    from eos.dd2.solver import beta_warm_start
    x0 = None
    for n_B in NB_GRID:
        p = solve_beta_eq_t0(par, n_B, x0=x0)
        x0 = beta_warm_start(p)
    assert p.n_B == NB_GRID[-1]


def test_no_muons_flag(par):
    p = solve_beta_eq_t0(par, 0.16, include_muons=False)
    assert p.n_mu == 0.0
    assert p.n_p == pytest.approx(p.n_e, rel=1e-9)
    # without muons the electron chemistry shifts
    assert p.mu_e != pytest.approx(GOLD_C["mu_e"], rel=1e-3)


if __name__ == "__main__":
    par = Parametrization.from_dd2_defaults()
    p = solve_beta_eq_t0(par, 0.16)
    got = dict(Y_p=p.Y_p, mstar_m=p.m_eff / par.m_nucleon, rho0=p.rho0,
               mu_e=p.mu_e, eps=p.eps, P=p.P, mu_n=p.mu_n, mu_p=p.mu_p)
    errs = {k: abs(got[k] / v - 1.0) for k, v in GOLD_C.items()}
    worst = max(errs, key=errs.get)
    print(f"golden beta-eq row n_B=0.16: max rel err = {errs[worst]:.2e} "
          f"({worst})   [HVH={p.hvh_rel:.1e}]")
    for k in GOLD_C:
        print(f"  {k:8s} {got[k]:12.5f}  gold {GOLD_C[k]:12.5f}  "
              f"rel {errs[k]:.2e}")
