"""Clear executed output from notebooks before committing them.

Embedded output is why `notebooks/ZLvMIT_hybrid.ipynb` reached 25 MB: base64
PNGs of every figure, stored in git and re-stored on every re-run. The source
cells are the thing worth versioning; the figures are regenerated by running
the notebook.

    python docs/strip_notebook_outputs.py                 # all notebooks
    python docs/strip_notebook_outputs.py a.ipynb b.ipynb # named ones
    python docs/strip_notebook_outputs.py --check         # report, change nothing

`--check` exits non-zero if any notebook still carries output, which is what a
pre-commit hook would call. Uses nbformat, which Jupyter already brings in, so
this adds no dependency.
"""
from __future__ import annotations

import sys
from pathlib import Path

import nbformat

REPO = Path(__file__).resolve().parent.parent


def strip(path: Path, check_only: bool = False) -> bool:
    """Clear outputs in one notebook. True if it had any."""
    nb = nbformat.read(path, as_version=nbformat.NO_CONVERT)

    dirty = False
    for cell in nb.cells:
        if cell.get("cell_type") != "code":
            continue
        if cell.get("outputs"):
            cell["outputs"] = []
            dirty = True
        if cell.get("execution_count") is not None:
            cell["execution_count"] = None
            dirty = True

    # Widget state is stored once for the whole notebook and can be megabytes
    # on its own, so it goes too.
    if nb.metadata.pop("widgets", None) is not None:
        dirty = True

    if dirty and not check_only:
        nbformat.write(nb, path)
    return dirty


def main(argv):
    check_only = "--check" in argv
    names = [a for a in argv if not a.startswith("--")]
    paths = ([Path(n).resolve() for n in names] if names
             else sorted((REPO / "notebooks").glob("*.ipynb")))

    had_output = []
    for path in paths:
        try:
            shown = path.relative_to(REPO)
        except ValueError:
            shown = path
        before = path.stat().st_size
        if strip(path, check_only=check_only):
            had_output.append(path)
            after = path.stat().st_size
            verb = "has output" if check_only else "stripped"
            print(f"{verb:9s} {shown}  "
                  f"{before / 1e6:.2f} MB -> {after / 1e6:.2f} MB")
        else:
            print(f"{'clean':9s} {shown}")

    if check_only and had_output:
        print(f"\n{len(had_output)} notebook(s) still carry output; run "
              f"`python docs/strip_notebook_outputs.py` before committing.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
